apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Rayuela Database Backup
# Daily backup of PostgreSQL databases to restic REST server
#
# Databases backed up: grexc, grext1, grext2
# Schedule: Daily at 02:00 AM (Argentina time)
# Retention: 7 daily, 4 weekly, 12 monthly

resources:
  - cronjob.yaml

configMapGenerator:
  - name: rayuela-backup-scripts
    files:
      - backup.sh
