apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - name: rayuela-db-init
    files:
      - init-databases.sh
