apiVersion: v1
kind: Service
metadata:
  name: rayuela-db
  labels:
    app.kubernetes.io/name: rayuela-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: rayuela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rayuela-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
