apiVersion: v1
kind: Service
metadata:
  name: rayuela
  labels:
    app.kubernetes.io/name: rayuela
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: rayuela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rayuela
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
